---
# tasks file for simple-apache
- name: install firewall, python3-firewall and httpd
  ansible.builtin.dnf:
    name:
      - httpd
      - firewalld
      - python3-firewall
    state: present

- name: Enable and start httpd
  ansible.builtin.systemd_service:
    name: httpd
    state: started
    enabled: true

- name: Permanently enable http service, also enable it immediately if possible
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: Template a file to /var/www/html
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify: Restart apache